---
language: go

environment:
  - OUTPUT_DIR=".build/output"
  - GO15VENDOREXPERIMENT="1"

facts:
  - git: "action=longhash"

services:
  - mysql: "db=test login=test:test"

pre:
  - go: "action=build -ldflags='-X main.version=0.2.3'"

test:
  - go: "action=test"
