---
language: go

environment:
  - OUTPUT_DIR=".build/output"
  - GO15VENDOREXPERIMENT="1"
  - VERSION="1.0.0"

facts:
  - git: "action=longhash"

services:
  - mysql

build:
  - go: "action=build ldflags='-X main.version=$$VERSION'"

test:
  - go: "action=test"
