---
language: .net

environment:
- CONFIGURATION="release"
- OUTPUT_DIR=".build/output"

facts:
  - git: "action=longhash"

services:
  - mssql
  # - iisexpress: "localhost:3333"
  # - iis: "localhost/something"

setup:
  - nuget: "action=restore"
  - gitversion: "updateassemblyinfo=true"

build:
  - msbuild: "path=*.sln targets=clean,build recurse=true"

test:
  - liquibase: "action=upgrade contexts=dll,test,something url=$$ARTIFACTORY_URL/$$MY/$$DB"
  - liquibase: "action=upgrade contexts=dll,test,something path=db"
  - host: "path=*app*.nupkg"
  - nunit: "files=*Tests*.dll recurse=true"

post:
  - sonar: ""
  - nuget: "path=*.nuspec"
  - nuget: "path=$$OUTPUT_DIR/*.nupkg"
