---
language: .net

environment:
- DB="dbconnenctionstring"
- MY="something_here"
- ARTIFACTORY_URL="hi"
- CONFIGURATION="release"
- OUTPUT_DIR=".build/output"

# facts:
# - nuget: "name=something"

services:
  - mssql: ""
  # - iisexpress: "localhost:3333"
  # - iis: "localhost/something"

pre:
  - nuget: "action=restore"
  - gitversion: "updateassemblyinfo=true"
  - msbuild: "path=*.sln targets=clean,build recurse=true"

test:
  - liquibase: "action=upgrade contexts=dll,test,something url=$$ARTIFACTORY_URL/$$MY/$$DB"
  - liquibase: "action=upgrade contexts=dll,test,something path=db"
  - host: "path=*app*.nupkg"
  - nunit: "files=*Tests*.dll recurse=true"

post:
  - sonar: ""
  - nuget: "path=*.nuspec"
  - nuget: "path=$$OUTPUT_DIR/*.nupkg"
